Frederikkoenig/fin 165 fix links in profile page
devhausleipzigacademy/camp12-final pull request #103
Opened 2024-09-10 15:08 UTC by Fredmpk

Fix all the links and also restrict the profile navnar for settings, update etc. to the owner of the profile

2024-09-11 13:02 UTC, Fredmpk commented
also added link to friends page

2024-09-12 07:27 UTC, dnmct requested changes

2024-09-12 07:27 UTC, dnmct commented on app/profile/[userId]/page.tsx
> +  async function logout(): Promise<ActionResult> {
you can put that function in `actions/auth.ts`, then you dont have to pass it as a prop. You can just use it in the HeaderNav

2024-09-12 07:29 UTC, dnmct requested changes

2024-09-12 07:29 UTC, dnmct commented on components/DrawerUpComingSessions.tsx
> +  defaultTable,
defaultTab

2024-09-12 09:22 UTC, dnmct approved these changes

2024-09-12 09:22 UTC, merged