Bensn/fin 203 make venue detail page fetch from db
devhausleipzigacademy/camp12-final pull request #110
Opened 2024-09-12 10:31 UTC by Hydrateurself

**Please Note:**

We should restrict the user on some inputs. Eg. A tag should be max 2 words. A description of a venue should have a fixed length of characters and a report also. In case something is too long we could truncate it . Still would be nice to restrict the user for too many input

2024-09-12 14:24 UTC, dnmct requested changes

2024-09-12 14:24 UTC, dnmct commented on app/venue-detail/page.tsx
> +  const venueId = "a9f7dd25-b7b9-47aa-8818-bdd170d520d9";
instead of hardcoding, move the page into `/venues/[venueId]` and get the venue id from params

2024-09-12 14:24 UTC, dnmct commented on prisma/migrations/20240912074602_new_schema/migration.sql
you can delete the migration

2024-09-13 10:00 UTC, TschonnyCache approved these changes

2024-09-13 10:01 UTC, merged