Hannes ffl/fin 124 update profile route
devhausleipzigacademy/camp12-final pull request #83
Opened 2024-09-04 09:25 UTC by hnns-dev

#124 update profile route

2024-09-09 07:17 UTC, dnmct requested changes, later dismissed

2024-09-09 07:17 UTC, dnmct commented on app/api/profile/user/route.ts
is this file used? if yes make it a server action

2024-09-10 08:10 UTC, louziferr commented on seed.ts
>    const musselGym = await prisma.venue.upsert({
Upsert only works when the Venue already exists. Please user prisma.venue.create instead. Or just use the seed file from main branch.

2024-09-10 08:11 UTC, louziferr commented on app/profile/me/page.tsx
> +  const ownUserId = "jhvrihll2lalvsug";
Please use the actual ID from the currently logged in user.

2024-09-10 08:12 UTC, louziferr commented on app/profile/page.tsx
This page shouldn't exists or only exist with a request parameter that is a user's ID. Please make responsive and request the profile page of an actual user from the DB, using their ID.

2024-09-10 13:59 UTC, louziferr approved these changes
very clean and cool! Nice job :)

2024-09-10 13:59 UTC, merged